kind: pipeline
type: docker
name: default

steps:
- name: build
  image: plugins/kaniko
  settings:
    username:
      from_secret: dockerusername
    password:
      from_secret: dockerpassword
    repo: mitaka8/playlist-bot
    tags: latest

- name: publish
  image: appleboy/drone-ssh
  settings:
    host:
      - irc.mitaka.nl
    username: root
    key:
      from_secret: ssh
  script:
   - docker pull mitaka8/playlist-bot
   - docker restart psbot
- name: announce
  image: appleboy/drone-discord
  settings:
    webhook_id:
      from_secret: discordwebhookid
    webhook_token:
      from_secret: discordwebhooktoken
    message: "New Playlist build pushed and released!"